(function(){
  const KEY='nagorikHub.userUpdates.v1',SETTINGS='nagorikHub.aiSettings.v1',LOG='nagorikHub.activityLog.v1';
  const defaults={enabled:true,autoCheck:true,onlineSearch:false,duplicateCheck:true,multiUserMatch:true,greenThreshold:90,manualThreshold:70,sourceBRTA:true,sourceDAM:true,sourceGov:true,sourceNews:true};
  const $=id=>document.getElementById(id),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=s=>(s??'').toString().replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let settings={...defaults,...read(SETTINGS,{})},rows=[];
  async function db(){if(window.supabaseClient)return window.supabaseClient;if(!window.supabase||!window.NAGORIK_SUPABASE_URL||!window.NAGORIK_SUPABASE_ANON_KEY)return null;window.supabaseClient=window.supabase.createClient(window.NAGORIK_SUPABASE_URL,window.NAGORIK_SUPABASE_ANON_KEY);return window.supabaseClient;}
  async function loadRows(){const d=await db();if(!d)return rows=read(KEY,[]);const{data,error}=await d.from('user_updates').select('*').order('created_at',{ascending:false}).limit(500);if(error)return rows=read(KEY,[]);return rows=(data||[]).map(x=>({id:x.id,category:x.category,reporterName:x.reporter_name,details:x.details,createdAt:x.created_at,status:x.status,aiFlag:x.ai_flag,adminStatus:x.admin_status||'pending',from:x.from,to:x.to,proposedValue:x.proposed_value,routeInfo:x.route_info,product:x.product,location:x.location,reportedDate:x.reported_date,title:x.title,targetType:x.target_type,reportCount:x.report_count,aiConfidence:x.ai_confidence,aiReason:x.ai_reason,aiSources:x.ai_sources||[],approvedAt:x.approved_at,rejectedAt:x.rejected_at,adminNote:x.admin_note}));}
  function log(action,row,note=''){const l=read(LOG,[]);l.push({id:'LOG-'+Date.now(),action,updateId:row?.id||'',note,at:new Date().toISOString()});write(LOG,l.slice(-300));}
  function title(x){return x.from?`${x.from} → ${x.to}`:x.product||x.title||'Update'}
  function renderStats(){const r=rows;$('sTotal').textContent=r.length;$('sAI').textContent=r.filter(x=>x.aiFlag).length;$('sPending').textContent=r.filter(x=>!['approved','rejected'].includes(x.adminStatus)).length;$('sApproved').textContent=r.filter(x=>x.adminStatus==='approved').length;$('sRejected').textContent=r.filter(x=>x.adminStatus==='rejected').length;}
  function badge(x){if(x.adminStatus==='approved')return '<span class="status-pill green">✅ Approved</span>';if(x.adminStatus==='rejected')return '<span class="status-pill red">❌ Rejected</span>';if(x.adminStatus==='need_evidence')return '<span class="status-pill yellow">🟡 Need Evidence</span>';return x.aiFlag?'<span class="status-pill green">🟢 AI Green Flag</span>':'<span class="status-pill yellow">🟡 Pending</span>';}
  function renderUpdates(filter='all'){let r=rows.slice();if(filter!=='all')r=r.filter(x=>x.category===filter);$('updatesList').innerHTML=r.length?r.map(x=>`<article class="admin-card"><div class="admin-card-top"><div><span class="tag">${esc(x.category)}</span><h3>${esc(title(x))}</h3></div>${badge(x)}</div><p><b>Proposed:</b> ${esc(x.proposedValue||x.details||'—')}</p>${x.location?`<p><b>Location:</b> ${esc(x.location)}</p>`:''}<p><b>Reports:</b> ${x.reportCount||1} · <b>AI confidence:</b> ${x.aiConfidence||0}% · <b>Submitted:</b> ${x.createdAt?new Date(x.createdAt).toLocaleString('en-GB'):'—'}</p>${x.aiReason?`<p class="muted">${esc(x.aiReason)}</p>`:''}<div class="admin-actions">${x.adminStatus!=='approved'?`<button class="btn" data-act="approve" data-id="${esc(x.id)}">✅ Approve & Publish</button>`:''}${x.adminStatus!=='rejected'?`<button class="btn danger" data-act="reject" data-id="${esc(x.id)}">❌ Reject</button>`:''}<button class="btn secondary" data-act="evidence" data-id="${esc(x.id)}">📝 Need Evidence</button></div></article>`).join(''):'<div class="empty">এই filter-এ কোনো update নেই।</div>';}
  function renderSources(){const s=[['BRTA','Bus fare / route','সরকারি','Active',settings.sourceBRTA],['DAM','বাজারদর','সরকারি','Active',settings.sourceDAM],['Government sources','নতুন তথ্য','সরকারি','Active',settings.sourceGov],['Trusted news','নতুন তথ্য','রেফারেন্স','Active',settings.sourceNews]];$('sourceTable').innerHTML=s.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]?'ON':'OFF'}</td></tr>`).join('');}
  function renderLog(){const l=read(LOG,[]).slice().reverse();$('logList').innerHTML=l.length?l.map(x=>`<div class="log-row"><b>${esc(x.action)}</b><span>${esc(x.updateId)}</span><span>${esc(x.note)}</span><time>${new Date(x.at).toLocaleString('en-GB')}</time></div>`).join(''):'<div class="empty">কোনো activity নেই।</div>';}
  function loadSettings(){['enabled','autoCheck','onlineSearch','duplicateCheck','multiUserMatch','sourceBRTA','sourceDAM','sourceGov','sourceNews'].forEach(k=>$(k).checked=!!settings[k]);$('greenThreshold').value=settings.greenThreshold;$('manualThreshold').value=settings.manualThreshold;}
  function saveSettings(){['enabled','autoCheck','onlineSearch','duplicateCheck','multiUserMatch','sourceBRTA','sourceDAM','sourceGov','sourceNews'].forEach(k=>settings[k]=$(k).checked);settings.greenThreshold=Math.max(1,Math.min(100,Number($('greenThreshold').value)||90));settings.manualThreshold=Math.max(1,Math.min(99,Number($('manualThreshold').value)||70));write(SETTINGS,settings);$('saveMsg').textContent='✓ AI settings saved';setTimeout(()=>$('saveMsg').textContent='',1800);log('AI settings updated',null,'');renderSources();renderLog();}
  async function action(id,type,note=''){const d=await db();if(!d)throw Error('Supabase connection unavailable');const patch=type==='approved'?{admin_status:'approved',status:'approved',approved_at:new Date().toISOString()}:type==='rejected'?{admin_status:'rejected',status:'rejected',rejected_at:new Date().toISOString() }:{admin_status:'need_evidence',status:'need_evidence',admin_note:note};const{error}=await d.from('user_updates').update(patch).eq('id',id);if(error)throw error;await loadRows();}
  document.querySelectorAll('.admin-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.admin-section').forEach(x=>x.hidden=true);b.classList.add('active');$(b.dataset.tab).hidden=false;if(b.dataset.tab==='activitySection')renderLog();}));
  $('updatesList').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const x=rows.find(a=>a.id===b.dataset.id);if(!x)return;try{if(b.dataset.act==='approve'){await action(x.id,'approved');log('Approved & published',x);}else if(b.dataset.act==='reject'){await action(x.id,'rejected');log('Rejected',x);}else{const note=prompt('কী evidence দরকার?','আরও নির্ভরযোগ্য source / ছবি / রসিদ প্রয়োজন।');await action(x.id,'evidence',note||'আরও evidence প্রয়োজন।');log('Need evidence',x,note||'');}renderStats();renderUpdates(document.querySelector('.update-filter.active')?.dataset.filter||'all');renderLog();}catch(err){alert('Update failed: '+err.message);}});
  document.querySelectorAll('.update-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.update-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderUpdates(b.dataset.filter);}));
  $('saveAI').addEventListener('click',saveSettings);$('resetAI').addEventListener('click',()=>{settings={...defaults};write(SETTINGS,settings);loadSettings();});
  (async()=>{loadSettings();await loadRows();renderStats();renderUpdates();renderSources();renderLog();})();
})();
