(function(){
  const KEY='nagorikHub.userUpdates.v1', SETTINGS='nagorikHub.aiSettings.v1', LOG='nagorikHub.activityLog.v1';
  const defaults={enabled:true,autoCheck:true,onlineSearch:true,duplicateCheck:true,multiUserMatch:true,greenThreshold:90,manualThreshold:70,sourceBRTA:true,sourceDAM:true,sourceGov:true,sourceNews:true};
  const $=id=>document.getElementById(id);
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=s=>(s??'').toString().replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let settings={...defaults,...read(SETTINGS,{})};
  const getRows=()=>read(KEY,[]); const saveRows=x=>write(KEY,x);
  function log(action,row,note=''){const logs=read(LOG,[]);logs.push({id:'LOG-'+Date.now(),action,updateId:row?.id||'',note,at:new Date().toISOString()});write(LOG,logs.slice(-300));}
  function title(x){return x.from?`${x.from} → ${x.to}`:x.product||x.title||'Update'}
  function renderStats(){const r=getRows();$('sTotal').textContent=r.length;$('sAI').textContent=r.filter(x=>x.aiFlag).length;$('sPending').textContent=r.filter(x=>!['approved','rejected'].includes(x.adminStatus)).length;$('sApproved').textContent=r.filter(x=>x.adminStatus==='approved').length;$('sRejected').textContent=r.filter(x=>x.adminStatus==='rejected').length;}
  function badge(x){if(x.adminStatus==='approved')return '<span class="status-pill green">✅ Approved</span>';if(x.adminStatus==='rejected')return '<span class="status-pill red">❌ Rejected</span>';if(x.adminStatus==='need_evidence')return '<span class="status-pill yellow">🟡 Need Evidence</span>';return x.aiFlag?'<span class="status-pill green">🟢 AI Green Flag</span>':'<span class="status-pill yellow">🟡 Pending</span>';}
  function renderUpdates(filter='all'){
    let r=getRows().slice().reverse(); if(filter!=='all')r=r.filter(x=>x.category===filter);
    $('updatesList').innerHTML=r.length?r.map(x=>`<article class="admin-card"><div class="admin-card-top"><div><span class="tag">${esc(x.category)}</span><h3>${esc(title(x))}</h3></div>${badge(x)}</div><p><b>Proposed:</b> ${esc(x.proposedValue||x.details||'—')}</p>${x.location?`<p><b>Location:</b> ${esc(x.location)}</p>`:''}<p><b>Reports:</b> ${x.reportCount||1} · <b>AI confidence:</b> ${x.aiConfidence||0}% · <b>Submitted:</b> ${new Date(x.createdAt).toLocaleString('en-GB')}</p>${x.aiReason?`<p class="muted">${esc(x.aiReason)}</p>`:''}${x.aiSources?.length?`<div class="source-list">${x.aiSources.map(s=>`<a href="${esc(s.url||'#')}" target="_blank" rel="noopener">${esc(s.title||s.url||'Source')}</a>`).join('')}</div>`:''}<div class="admin-actions">${x.adminStatus!=='approved'?`<button class="btn" data-act="approve" data-id="${x.id}">✅ Approve & Publish</button>`:''}${x.adminStatus!=='rejected'?`<button class="btn danger" data-act="reject" data-id="${x.id}">❌ Reject</button>`:''}<button class="btn secondary" data-act="evidence" data-id="${x.id}">📝 Need Evidence</button></div></article>`).join(''):'<div class="empty">এই filter-এ কোনো update নেই।</div>';
  }
  function renderSources(){const sources=[['BRTA','Bus fare / route','সরকারি','Active',settings.sourceBRTA],['DAM','বাজারদর','সরকারি','Active',settings.sourceDAM],['Government sources','নতুন তথ্য','সরকারি','Active',settings.sourceGov],['Trusted news','নতুন তথ্য','রেফারেন্স','Active',settings.sourceNews]];$('sourceTable').innerHTML=sources.map(s=>`<tr><td>${s[0]}</td><td>${s[1]}</td><td>${s[2]}</td><td>${s[3]}</td><td>${s[4]?'ON':'OFF'}</td></tr>`).join('');}
  function renderLog(){const logs=read(LOG,[]).slice().reverse();$('logList').innerHTML=logs.length?logs.map(x=>`<div class="log-row"><b>${esc(x.action)}</b><span>${esc(x.updateId)}</span><span>${esc(x.note)}</span><time>${new Date(x.at).toLocaleString('en-GB')}</time></div>`).join(''):'<div class="empty">কোনো activity নেই।</div>';}
  function loadSettings(){['enabled','autoCheck','onlineSearch','duplicateCheck','multiUserMatch','sourceBRTA','sourceDAM','sourceGov','sourceNews'].forEach(k=>$(k).checked=!!settings[k]);$('greenThreshold').value=settings.greenThreshold;$('manualThreshold').value=settings.manualThreshold;}
  function saveSettings(){['enabled','autoCheck','onlineSearch','duplicateCheck','multiUserMatch','sourceBRTA','sourceDAM','sourceGov','sourceNews'].forEach(k=>settings[k]=$(k).checked);settings.greenThreshold=Math.max(1,Math.min(100,Number($('greenThreshold').value)||90));settings.manualThreshold=Math.max(1,Math.min(99,Number($('manualThreshold').value)||70));write(SETTINGS,settings);$('saveMsg').textContent='✓ AI settings saved';setTimeout(()=>$('saveMsg').textContent='',1800);log(null,null,'AI settings updated');renderSources();renderLog();}
  document.querySelectorAll('.admin-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.admin-section').forEach(x=>x.hidden=true);b.classList.add('active');$(b.dataset.tab).hidden=false;if(b.dataset.tab==='activitySection')renderLog();}));
  $('updatesList').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const rows=getRows(),x=rows.find(a=>a.id===b.dataset.id);if(!x)return;if(b.dataset.act==='approve'){x.adminStatus='approved';x.status='approved';x.approvedAt=new Date().toISOString();log('Approved & published',x);}else if(b.dataset.act==='reject'){x.adminStatus='rejected';x.status='rejected';x.rejectedAt=new Date().toISOString();log('Rejected',x);}else{const note=prompt('কী evidence দরকার?','আরও নির্ভরযোগ্য source / ছবি / রসিদ প্রয়োজন।');x.adminStatus='need_evidence';x.status='need_evidence';x.adminNote=note||'';log('Need evidence',x,x.adminNote);}saveRows(rows);renderStats();renderUpdates(document.querySelector('.update-filter.active')?.dataset.filter||'all');renderLog();});
  document.querySelectorAll('.update-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.update-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderUpdates(b.dataset.filter);}));
  $('saveAI').addEventListener('click',saveSettings);$('resetAI').addEventListener('click',()=>{settings={...defaults};write(SETTINGS,settings);loadSettings();});
  loadSettings();renderStats();renderUpdates();renderSources();renderLog();
})();
