// Auto-generated by .github/workflows/daily-update.yml
// Do not edit manually. If this file is absent, the static fallback remains active.
window.NAGORIK_LIVE = {
  "updatedAt": "2026-09-15T00:00:00Z",
  "market": {},
  "retail": {},
  "bus": {
    "routes": [],
    "updated": "2026-04-23",
    "source": "BRTA"
  }
};
