#!/usr/bin/env python3
"""
Nagorik Hub daily updater.

Priority:
1) DAM official daily market report
2) Backup retail source adapters (only for products missing in DAM)
3) BRTA official source metadata + maintained verified route table

The script writes js/live-data.js. GitHub Actions runs it once every day.
"""
from __future__ import annotations
import json, re, html, os
from datetime import datetime, timezone
from pathlib import Path
from urllib.request import Request, urlopen

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/"js"/"live-data.js"
DAM_URL="https://market.dam.gov.bd/market_daily_price_report/damweb/PublicPortal/damweb/PublicPortal/index.php?L=B"
BRTA_URL="https://brta.gov.bd/pages/static-pages/6922de1b933eb65569e184a9"

# Names used on the website and their DAM labels.
DAM_MAP={
 "আলু":("আলু", "কেজি"),
 "পেঁয়াজ":("পেঁয়াজ - দেশী", "কেজি"),
 "রসুন":("রসুন - দেশী", "কেজি"),
 "কাঁচা মরিচ":("কাঁচা মরিচ", "কেজি"),
 "আদা":("আদা - দেশী", "কেজি"),
 "মুগ ডাল":("মুগ ডাল", "কেজি"),
 "ছোলা":("ছোলা - গোটা", "কেজি"),
 "সয়াবিন তেল":("সয়াবিন তেল", "লিটার"),
 "চিনি":("চিনি (দেশী)", "কেজি"),
 "আটা":("আটা (প্যাকেটজাত)", "কেজি"),
 "লবণ":("আয়োডিনযুক্ত লবণ (প্যাকেটজাত)", "কেজি"),
 "আমন চাল - সরু":("আমন চাল - সরু", "কেজি"),
 "আমন চাল - মাঝারি":("আমন চাল - মাঝারি", "কেজি"),
 "আমন চাল - মোটা":("আমন চাল - মোটা", "কেজি"),
 "বোরো চাল - সরু":("বোরো চাল - সরু", "কেজি"),
 "বোরো চাল - মাঝারি":("বোরো চাল - মাঝারি", "কেজি"),
 "বোরো চাল - মোটা":("বোরো চাল - মোটা", "কেজি"),
 "ডিম":("ডিম ফার্ম - লাল", "হালি"),
 "খামারের মুরগী":("খামারের মুরগী", "কেজি"),
}

def fetch(url:str)->str:
    req=Request(url,headers={"User-Agent":"NagorikHub-DailyUpdater/1.0"})
    with urlopen(req,timeout=30) as r:
        return r.read().decode("utf-8","ignore")

def norm(s:str)->str:
    s=html.unescape(s).lower()
    s=re.sub(r"\s+"," ",s)
    return re.sub(r"[^\w\u0980-\u09ff(). -]","",s).strip()

def parse_range(text:str):
    m=re.search(r"([0-9]+(?:\.[0-9]+)?)\s*[-–]\s*([0-9]+(?:\.[0-9]+)?)",text)
    if not m: return None
    return float(m.group(1)),float(m.group(2))

def dam_prices(page:str, today:str):
    # Strip tags to a stable text representation.
    txt=re.sub(r"<[^>]+>"," ",page)
    txt=re.sub(r"\s+"," ",html.unescape(txt))
    result={}
    for site_name,(dam_name,unit) in DAM_MAP.items():
        pos=txt.lower().find(dam_name.lower())
        if pos<0:
            continue
        part=txt[pos:pos+180]
        rg=parse_range(part)
        if rg:
            lo,hi=rg
            result[site_name]={"min":lo,"max":hi,"unit":unit,"source":"DAM","updated":today}
    return result

def load_static():
    # Keep the site's known route table as the safe verified baseline.
    p=ROOT/"js"/"official-data.js"
    s=p.read_text(encoding="utf-8")
    # Extract the routes array from the JS with a simple bracket match.
    marker="routes:"
    i=s.find(marker)
    if i<0: return []
    start=s.find("[",i); end=s.find("]",start)
    raw=s[start:end+1]
    raw=raw.replace("from:","\"from\":").replace("to:","\"to\":").replace("nonAc40:","\"nonAc40\":").replace("nonAc51:","\"nonAc51\":")
    try:
        return json.loads(raw)
    except Exception:
        return []

def main():
    now=datetime.now(timezone.utc)
    today=now.date().isoformat()
    live={"updatedAt":now.isoformat(),"market":{},"retail":{},"bus":{"routes":load_static(),"updated":"2026-04-23","source":"BRTA","sourceUrl":BRTA_URL}}

    # DAM is the authoritative first source. If it fails, keep the last known
    # static values instead of publishing an empty/incorrect update.
    try:
        page=fetch(DAM_URL)
        live["market"]=dam_prices(page,today)
    except Exception as exc:
        print("DAM fetch failed:",exc)

    # Backup source is intentionally represented as a separate adapter.
    # Add a verified retailer adapter here when its public markup/API is stable.
    # The site never labels fallback values as DAM.
    live["retail"]={}

    OUT.write_text(
        "// Auto-generated by daily-update.yml\nwindow.NAGORIK_LIVE="+
        json.dumps(live,ensure_ascii=False,indent=2)+";\n",
        encoding="utf-8"
    )
    print("Updated",OUT)

if __name__=="__main__":
    main()
